server:
  port: 8081


management:
  server:
    ## 访问端口
    port: 8081
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - shutdown
          
start:
  rpc:
    enable: true  

cosysun:
  server:
    api: rpc-server-test
   
rpc:
  server:
    port: 10001
  zk:
    addr: 192.168.56.10:2181
  policy:
    tcp: echoClient
    zk: cuatorServerRegisterAdaptor
    discovery: cuatorServerDiscoveryAdaptor
    loadbalance: randomAdaptor
    zip: jdkZipAdaptor
    serial: kryoSerialAdaptor   