server:
  port: 8769
spring:
  application:
    name: demo-admin
  cloud:
    zookeeper:
      connect-string: test:2181
      enabled: true
      discovery:
        enabled: true
        register: true