server:
  port: 7970
spring:
  application:
    name: tx-lcn-tm
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.56.10:3306/test?useUnicode=true&characteerEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  redis:
    host: test
    port: 6379
