server:
  port: 10002
  
spring:
  application:
    name: demo-redis
  cache:
    type: redis
    redis:
      time-to-live: 36000000
      cache-null-value: true
  
management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 
          "*"