server:
  port: 10001
  
spring:
  application:
    name: simple-boot-project
    url: redis://test:6379
  cloud:
    zookeeper:
      connect-string: test:2181
      enabled: true
      discovery:
        enabled: true
        register: true
feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 20000
  hystrix:
    enabled: true
hdfs:
  url: hdfs://192.168.56.10:9000
  username: root
  replication: 2
  blocksize: 67108864
  
management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 
          "*"