server:
  port: 10001
  
spring:
  application:
    name: simple-boot-project
  cloud:
    zookeeper:
      connect-string: test:2181
      enabled: true
      discovery:
        enabled: true
        register: true
  data:
    mongodb:
      uri: mongodb://test:27017/test    
feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 20000
  hystrix:
    enabled: true
management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 
          "*"