server:
  port: 10001
  
spring:
  application:
    name: simple-boot-project
  mail:
    host: smtp.163.com
    port: 465
    username: 
    password: 
    default-encoding: utf-8
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true