server:
  port: 10001
  
spring:
  application:
    name: demo-kafka
  kafka:
    bootstrap-servers: test:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: kafka-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cloud:
    zookeeper:
      connect-string: test:2181
      enabled: true
      discovery:
        enabled: true
        register: true
feign:
  client:
    config:
      default:
        connect-timeout: 10000
        read-timeout: 20000
  hystrix:
    enabled: true
management:
  server:
    port: 8081
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: 
          "*"